backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "img"

collections:
  - name: "cuentas"
    label: "Cuentas de Free Fire"
    folder: "content/cuentas"
    create: true
    fields:
      - {label: "Título de la cuenta", name: "title", widget: "string"}
      - {label: "Categoría", name: "categoria", widget: "select", options: ["veteranas", "top"]}
      - {label: "Detalles / Descripción", name: "detalle", widget: "text"}
      - {label: "Precio", name: "precio", widget: "string"}
      - {label: "Foto de la cuenta", name: "image", widget: "image"}